# Generated by Django 2.0.1 on 2018-01-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book_language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Mandarin', 'Mandarin'), ('French', 'French'), ('Yiddish', 'Yiddish'), ('German', 'German'), ('Russian', 'Russian'), ('Pig Latin', 'Pig Latin'), ('Other', 'Other')], default='English', help_text='language this book is written in', max_length=10),
        ),
    ]
